;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        change-inner
        company-complete
        describe-key-briefly
        easy-kill
        indent-for-tab-command
        kill-rectangle
        prelude-move-beginning-of-line
        prelude-smart-open-line
        ruby-tools-to-single-quote-string
        sh-assignment
        sldb-quit
        slime-autodoc-space
        smex
        sp--self-insert-command
        sp-kill-symbol
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        haml-electric-backspace
        js2-mode-show-node
        markdown-exdent-or-delete
        mouse-drag-vertical-line
        neotree-find
        slime-close-all-parens-in-sexp
        ))
