;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        change-inner
        describe-key-briefly
        easy-kill
        indent-for-tab-command
        kill-rectangle
        prelude-move-beginning-of-line
        sp--self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        ))
